project:
  type: website
  output-dir: docs
  pre-render: python3 organize-bibliography.py

# Meta
description-meta: "Emily K. Johnson Professional Website"
author-meta: "Emily Johnson"

website:
  title: "Emily Johnson"
  image: "https://quarto.org/quarto.png"
  description: "Professional Website of Emily K. Johnson"
 
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd

    right:
      - text: CV
        href: files/cv.pdf
      - icon: github
        href: https://github.com/
        target: _blank
  
  page-navigation: true
  
  page-footer:
    left: "Emily K. Johnson &copy; <script>document.write(new Date().getFullYear())</script>"
    right:
      - icon: github
        href: https://github.com/
        target: _blank  
  
  open-graph: true

  site-url: "https://yourusername.github.io/quarto-professional-website-emily"
  
bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

